version: '3'
services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '3050:80'
  postgres:
    image: 'postgres:latest'
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=welcome123
  
  redis:
    image: 'redis'
  
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=welcome123
      - PGPORT=5432
  client:
    environment:
      - WDS_SOCKET_PORT=0
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

